### ISSUE TITLE
Why is WH02 so bad? Not bad sequence with samtools consensus

### ISSUE THREAD

**Issue by babarlelephant** [niemasd/PRJCA008874-Analysis#1]
Hi, this is what I obtained by downloading your merged bams and doing 

`samtools consensus -m bayesian  --use-qual --call-fract 0.75 -a --min-depth 10 bamfile.bam -o seq.fasta  --show-del yes --show-ins no`

Any guess on why it gives such a different result for WH02? Your [consensus sequence](https://github.com/niemasd/PRJCA008874-Analysis/blob/main/data/consensus/SAMC703647.06.consensus.fa) has 27512 N

The fasta I got: https://wtools.io/paste-code/bC6N

mutations wrt Wuhan-Hu-1

```
WH01
  N :60
  - :4
WH02
  A1381G G3135C A5202T G7500A T7826A A9121T T10061C C11006A T11503A T14878G G15907C G18506A G18523C C19374T C22109G A24339T G24932C C24937T
  N :949
  - :62
WH03
  N :21
  - :1
WH04
  C8782T T28144C
  N :17
  - :0
WH19001
  A12T G20670A G20679A A29638T T29655C G29705T C29743T
  N :1120
  - :0
WH19004
  N :96
  - :0
WH19008
  A12T G20670A G20679A A24325G
  N :702
  - :0
YS8011
  N :41
  - :0
```

**Comment by babarlelephant** [comment]
For the coverage plot that I got
![image](https://user-images.githubusercontent.com/6537565/173105952-8bb9fdb3-16db-44ae-a94e-7029b42a0659.png)
quite different to yours 
![image](https://user-images.githubusercontent.com/6537565/173105979-d875980a-8d27-4c8b-82f1-764ce83a63ce.png)

**Comment by niemasd** [comment]
Pulling up the [base counts for that sample](https://github.com/niemasd/PRJCA008874-Analysis/blob/main/data/sambamviz/SAMC703647.03.sambamviz.out/nuc_count_NC_045512.2.tsv) and visualizing them in [SamBamViz](https://niemasd.github.io/SamBamViz), that region is extremely low-coverage (ranging between 2 to 4 reads per site):

![visualization](https://user-images.githubusercontent.com/4195510/173107096-c722facd-beb8-4ba7-ae2b-b0dedd436f57.jpg)

*Note that the SamBamViz visualization uses 0-based indexing, not 1-based*

**Comment by niemasd** [comment]
Regarding the differences in coverage plots:

(1) Are you using the trimmed BAM rather than the raw BAM? Your [Pastebin](https://wtools.io/paste-code/bC6N) says "niemasd ***merged BAM*** then samtools consensus", which  makes me think that you're using the [untrimmed merged BAMs](https://github.com/niemasd/PRJCA008874-Analysis#13-merging-bams) rather than the [trimmed BAMs](https://github.com/niemasd/PRJCA008874-Analysis#2-trimming-bams--sorting-trimmed-bams). You should be using the [trimmed BAMs](https://github.com/niemasd/PRJCA008874-Analysis/blob/main/data/trimmed_bam).

(2) [I'm using a minimum base quality score of 20](https://github.com/niemasd/PRJCA008874-Analysis#3-calculating-coverage--stats) when I call SamBamViz to generate the plot, but you're not filtering by quality score as far as I can tell. In general, low-quality base calls need to be ignored in all steps of the analysis (I use a threshold of 20 as per the iVar recommendations)

**Comment by babarlelephant** [comment]
Yes I'm using the merged untrimmed bams, which gives a reasonable coverage and sequence, 
you are perfectly right that filtering for quality needs to be done,
but your filtering step may be too stringent at least for WH02.

Thank you!

**Comment by niemasd** [comment]
> but your filtering step may be too stringent at least for WH02

I'm not sure what you mean by this. A base quality score of 20 means 99% accuracy, and trimming/ignoring base calls with quality <20 is standard not only in viral genomics, but in most (all?) sequencing contexts:

https://galaxyproject.github.io/training-material/topics/sequence-analysis/tutorials/quality-control/tutorial.html

If the coverage drops below a reasonable level after using a base call quality threshold of 20, "This might be too strict" is not the correct interpretation: the correct interpretation is "This sample has too few high-quality base calls covering these positions" (which is precisely what `N` in the consensus sequence denotes).
